name: Finals Orchestrator

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-brute:
    runs-on: ubuntu-latest
    steps:
      - name: brute tests
        uses: actions/checkout@v4
      - name: Install pytest
        run: pip install pytest pytest-spec pytest-describe pytest-mock
      - name: Run pytest
        run: pytest test_brute.py --spec 
  test-christmas:
    runs-on: ubuntu-latest
    steps:
      - name: christmas tests
        uses: actions/checkout@v4
      - name: Install pytest
        run: pip install pytest pytest-spec pytest-describe
      - name: Run pytest
        run: pytest test_christmas.py --spec 
    
